language: node_js
node_js:
  - "node"
  - "iojs"
  - "5"
  - "4"
  - "0.12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
git:
  depth: 3
install: npm install gulp gulp-util gulp-file yargs sinon istanbul
before_script:
  - 'gulp build:dev'
after_success:
  - 'npm run coveralls'
